@startuml


class edu.hm.cs.katz.swt2.agenda.AgendaApplication {
    {static} + main()
}




class edu.hm.cs.katz.swt2.agenda.AgendaConfiguration {
    + modelMapper()
    # configure()
}

  

  edu.hm.cs.katz.swt2.agenda.AgendaConfiguration -up-|> org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter



@enduml
