@startuml

class edu.hm.cs.katz.swt2.agenda.common.SecurityHelper {
    {static} + ADMIN_AUTHORITY : GrantedAuthority
    {static} + ADMIN_ROLE : String
    {static} + ADMIN_ROLES : Collection<GrantedAuthority>
    {static} + STANDARD_ROLES : Collection<GrantedAuthority>
    {static} + escalate()
    {static} + isAdmin()
}


enum StatusEnum {
  FERTIG
  NEU
  OFFEN
}


class edu.hm.cs.katz.swt2.agenda.common.UuidProviderImpl {
    + getRandomUuid()
}

@enduml
