@startuml

' Layout
skinparam classAttributeIconSize 0
skinparam monochrome true
skinparam shadowing false
skinparam DefaultFontName arial
skinparam DefaultFontSize 12
skinparam ClassFontStyle bold

'User
object "<u>fine:User</u>" as fine{
    login = "fine"
    password = "#Fine2020"
    name = "Fine"
    admin = false
    status
}
object "<u>ernie:User</u>" as ernie{
    login = "ernie"
    name = "Ernie"
    password = "#Ernie2020"
    admin = false
    status 2
}
object "<u>bert:User</u>" as bert{
    login = "bert"
    name = "Bert"
    password = "#Bert2020"
    admin = false
    status 6
}
object "<u>admin:User</u>" as admin{
    login = "admin"
    name = "Administrator"
    password = "#Admin2020"
    admin = true
    status statusadmin
}

'Topics
object "<u>HTMLKurs: Topic</u>" as HTMLKurs{
    title = "HTML für Anfänger"
    shortDescription = "Dieser Kurs behandelt die Grundlagen von HTML."
    longDescription = "Die Hypertext Markup Language ist eine [...]"
    UUID = e17ae604-2b50-469a-bba0-b5b4543580b3
    CREATOR_LOGIN= "fine"

}
object "<u>CSSKurs: Topic</u>" as CSSKurs{
    title = "CSS für Fortgeschrittene"
    shortDescription = "Dieser Kurs richtet sich an Fortgeschrittene und behandelt CSS."
    longDescription = "Cascading Style Sheets, kurz CSS genannt, ist eine [...]"
    UUID = c3ef0536-dd96-4968-a9b3-4bad0c13d1e0
    CREATOR_LOGIN = "fine"
}
object "<u>BackKurs: Topic</u>" as BackKurs{
    title = "Ernies Backkurs"
    shortDescription = "Lernen Sie Backen mit Ernie."
    longDescription = "Hier lernen Sie innerhalb kürzester Zeit das Backen wie ein Konditor."
    UUID = 85b55409-d34d-4985-9da5-8c8acd06fe23
    CREATOR_LOGIN = "ernie"
}

'Tasks
object "<u>LinkErstellen: Task</u>" as LinkErstellen {
    ID = 1
    title = "Link erstellen"
    TOPIC_UUID = e17ae604-2b50-469a-bba0-b5b4543580b3
}
object "<u>HTMlErstellen: Task</u>" as HTMlErstellen {
    ID = 3
    title = "Leeres HTML-Template erstellen"
    TOPIC_UUID = e17ae604-2b50-469a-bba0-b5b4543580b3
}
object "<u>Googlehupf: Task</u>" as Googlehupf {
    ID = 4
    title = "Googlehupf backen"
    TOPIC_UUID = 85b55409-d34d-4985-9da5-8c8acd06fe23
}
object "<u>Affenmuffins: Task</u>" as Affenmuffins {
    ID = 5
    title = "Affenmuffins backen"
    TOPIC_UUID = 85b55409-d34d-4985-9da5-8c8acd06fe23
}

'status
object "<u>2: status</u>" as 2{
	id = 2
	user = "ernie"
	task = 1
	status = "fertig"
}

object "<u>6: status</u>" as 6{
	id = 6
	user = "bert"
	task = 5
	status = "fertig"
}

'Assoziationen
fine -- HTMLKurs :> erstellt
fine -- CSSKurs :> erstellt
ernie -- BackKurs :> erstellt

ernie -- 2 :> besitzt
bert -- 6 :> besitzt

ernie -- HTMLKurs :> abboniert
bert -- BackKurs :> abboniert

HTMLKurs -- LinkErstellen :< gehört zu
HTMLKurs -- HTMlErstellen :< gehört zu

6 -- Affenmuffins :> bezieht sich
2 -- LinkErstellen :> bezieht sich

BackKurs -- Googlehupf :< gehört zu
BackKurs -- Affenmuffins :< gehört zu


@enduml